primitiveClasses = ...
    {'low_shrub', 'low_shrub_patch', ...
    'small_shrub','small_shrub_patch', ...
    'medium_shrub', 'medium_shrub_patch', ...
    'large_shrub', 'large_shrub_patch', ...
    'small_tree', ...
    'medium_tree', ...
    'large_tree'};

save('../data/primitive_classes','primitiveClasses');