# * section id: . query type: . sim type: . version: . tag: 

- mat scrutiny pipeline
  - check if appropriate sim version dirs exist in mat
  - convert sim detail txt to mat
  - convert models to mat
    - if hg models created in cpp, save to mat
    - if new scene hg, then ellipsoids will exist as mats
    - for tri models, ground tri will be needed in the mm_sim directory
      - use reduced scene tri models
  - lookat equispaced packets, random rays in each

----------------------------------------------------------------------------------------------------

* section id: 8. query type: section. sim type: hg. version: 250417.
- packet idx 1349
  - ray idx 318, 382, 383, 320
    - sim rays didn't penetrate vegetation
  - ray idx 30, 62, 64
    - sim hits but real doesn't. maybe not enough true miss information.
  - ray idx 247
    - ellipsoids too large, not transparent enough
- packet idx 2024
  - ray idx 128 256 368 305
    - false hit
  - ray idx 313 252
    - sim pt blocked early. i think stochastic.
  - ray idx 107 38
    - in dense vegetation, ray intersects a number of ellipsoids. max maha dist
      probably too large.
  - ray idx 272 267
    - good job penetrating through vegetation.
- packet idx 2699   
  overall looks like much larger variance than real data
  - ray idx 365 72
    - false hit. also ellipsoids very large.
  - ray idx 169 273 106
    - ellipsoids too large. gaussian samples have a high variance.
  - ray idx 172
    - good job in thicket. but got lucky in the high variance
- packet idx 3374
  - ray idx 369 225 289 323 76
    - false hit, from ground triangles. probably need better hit prob calc.
  - ray idx 195
    - good job. hitting ground :P
  - ray idx 343
    - hits too early. ellipsoids not transparent enough.
  - ray idx 211
    - false miss. no ground tri where there should of been
  - ray idx 313
    - the good job analogue of ray idx 343.
  - ray idx 378 188
    - false ellipsoid hit. embarassingly large variance.
  - ray idx 344
    - medium job. smaller variance could be better

----------------------------------------------------------------------------------------------------

* section id: 4. query type: slice. sim type: hg. version: 080917.
- packet idx 410. for many true hits, sim range lower than real. could be shape
  error, or not permeable enough. although the low precision makes me think too
  permeable?
  - ray idx 14
    - false hit. perhaps ellipsoids large variance. but otherwise sim looks to
      be doing job. unclear why real missed.
  - ray idx 98, 65
    - false miss. seems like a good case of not having enough ellipsoids at the
      right place. shape error. in this case, i should also be visualizing
      nearby annotations.
  - ray idx 149, 113
    - false hit. here sim hit some bushes farther down. again why real missed
      unclear.
  - ray idx 201, 176, 207
    - medium job. in shrubs. how to present? that semantic segmented correctly,
      and then the primitive ellipsoids transferred over well?
  - ray idx 214
    - false hit. but this time on faraway ground.

- packet idx 37. ground packet. seems like a small ground patch was missed by
  ground tri modeling

- packet idx 695. overall looks like good job.
  - ray idx 208
    - good job. good example of simulating low shrub patch.
  - ray idx 210, 301
    - medium job.
  - ray idx 85, 213
    - large error. in shrub patch area, but sim got caught in early shrub, while
      real hit ground much later.
  - ray idx 130
    - false hit. but looks like ray pointing right at the ground, so real miss
      mysterious.
  - ray idx 240
    - false hit. sim hits far shrubs, while ground misses. seems like opposite
      of 85.

- packet idx 159
  - ray idx 20, 19
    - large error. in shrub patch area, but sim got caught in early shrub, while
      real hit ground much later.
  - ray idx 63, 384, 153, 89
    - false hit. sim hits a tree. bad annotation?
  - ray idx 65
    - false hit. but looks like ray pointing right at the ground, so why real miss?
  - ray idx 263, 359
    - good job. but ground, so no credit.

- packet idx 581. another veg seems to generate sim hits for which real wasn't
  present. bad segment/ anno?

- packet idx 219. seems like good job with some low shrubs. but extraneous
  bigger ellipsoids are there?
  - ray idx 106
    - large error. sim hits early ell, real hits perhaps ground.
  - ray idx 338, 291, 301, 20, 49, 368
    - false hit. also large-ish variance. ray in thicket, so why real miss?
  - ray idx 126, 61
    - false hit. extraneous ellipsoids?
  - ray idx 313, 243, 107
    - good job. hits veg. so was the shape off which gave extraneous
      ell?

- packet idx 563. should be interesting because real and sim hit veg. so shape,
  anno etc can factor in. good shape overall.
  - ray idx 252
    - medium job. perhaps shape not exact match etc.
  - ray idx 286, 343, 58, 219
    - medium job. both hit tree. i think there might be ellipsoids shape issue,
      which prevents good job.

- packet idx 9. good shape test
  - ray idx 120, 88, 59, 56
    - false hit. sim hits far ell. why does real miss, check anno, primitives.
  - ray idx 207, 328, 142, 300, 362
    - false miss. too permeable ell?
  - ray idx 17
    - false hit. seems like opposite of earlier.
  - ray idx 100, 70, 
    - false hit. seems like opposite of 207. the two together might be a good
      candidate for stochasticity
  - ray idx 212
    - good job. hit shrub patch.
  - ray idx 155, 93, 91
    - good job. hit far ell, very nice
  - ray idx 250
    - false hit. opp of 155.

- packet idx 654. good shape test
  - ray idx 187
    - large error. real nearer than sim. some ellipsoids shape mismatch perhaps.
  - ray idx 172, 196, 100, 232
    - false miss. stochastic?
  - ray idx 314, 337
    - false hit. sim hits far veg.
  - ray idx 248
    - large error. shape mismatch?
  - ray idx 135
    - large error. sim nearer due to some shrubs.
  - ray idx 240, 80
    - good job.
  - ray idx 181, 87
    - good job. shrubs.
  - ray idx 120
    - large error. sim nearer than real. doesn't seem like ellipsoids near real?
  - ray idx 166
    - large error. sim nearer. shrubs
  - ray idx 169
    - medium job. same situation as 166. large ell variance?
  - ray idx 86
    - large error. in shrubs. large ell variance?

- packet idx 209
  - ray idx 163, 33, 308, 370, 38, 129, 12
    - false hit. ray passes through shrub patch. why does real miss?
  - ray idx 357, 201, 269
    - large error. true hit version of 163?
  - ray idx 261, 275
    - medium error. version of 357.
  - ray idx 238
    - good job.
  - ray idx 278
    - medium job. so was the shrub overdone?

- packet idx 122. one veg in sight
  - ray idx 189
    - good job. hit far veg.
  - ray idx 21
    - false hit. sim hits shrub patch. why does real miss? overdone shrub patch?
  - ray idx 211
    - large error. lost in shrubs.
  - ray idx 161
    - good job. in shrubs. stochastic.

- packet idx 90. large shrubs looks like overall.
  - ray idx 243, 308, 305
    - good job. hits side shrubs.
  - ray idx 368, 162, 327, 261
    - false hit. 
  - ray idx 267, 169, 172
    - good job. low shrub patch.

- packet idx 195. veg in sight
  - ray idx 46, 107
    - medium job. large ell var.
  - ray idx 195
    - good job.
  - ray idx 343, 211, 243, 61, 327
    - false hit. why?
  - ray idx 313, 49, 308, 305, 261
    - good job. in tree.
  - ray idx 252, 272
    - medium job. in tree.

- packet idx 
  - ray idx 
  - ray idx 
  - ray idx 
  - ray idx 
  - ray idx 
  - ray idx 

- packet idx 669. veg.
- packet idx 539. example for good ground.

----------------------------------------------------------------------------------------------------

* section id: 4. query type: slice. sim type: mm. version: 280817

- packet idx 675. diff shape between sim and real veg?
  - ray idx 225, 289, 323, 357
    - false hit. in shrubs. why did real miss?
  - ray idx 195
    - medium job. true hit version of 225.
  - ray idx 211, 313, 147
    - large error. effect of no permeability for mm. also seems like error in mm
      veg shape.
  - ray idx 76, 237
    - good job. version of 195.
  - ray idx 136
    - false miss. did the anno get this wrong?

- packet idx 54. one tree in line of sight. mm veg shape diff from real? lots of
  ground pts.

- packet idx 4. some shrubs in sight.
  - ray idx 33, 334, 328, 161
    - false hit. in shrubs. 
  - ray idx 100, 70, 135, 71, 130, 38
    - good job. in shrubs. less var than ell, which seems to be better.
  - ray idx 166
    - false miss. version of 100. mm shrubs can't do mixed pixels.

- packet idx 456. nothing remarkable. mostly ground
  - ray idx 357, 337
    - false hit. pointing at ground.
  - ray idx 348
    - false hit. sim hits veg far away. should prob of hit reduce with range?
  - ray idx 456
    - false miss. from ground. seems stochastic.

- packet idx 344. mostly ground. potential bushes perm 0 example.

- packet idx 27. lots of ground. some veg in line of sight. why is this case
  coming up so often?
  - ray idx 348
    - false miss. looks like anno got it right, but the surface nature meant
      that ray-tri intersection was missed
  - ray idx 249
    - large error. real stopped by nearer veg.

- packet idx 90. lots of veg.
  - ray idx 308, 305, 267, 72, 273
    - good job. in shrubs.
  - ray idx 107, 169, 172
    - medium job. in shrubs
  - ray idx 368, 365, 294
    - false hit. ray directed at shrubs.
  - ray idx 327, 90, 38
    - large error. in shrubs.

- packet idx 195. great example of no perm in mm.
  - ray idx 252, 313
    - medium job. example of no perm.
  - ray idx 46
    - false miss. anno problem perhaps.
  - ray idx 369
    - false hit. why?
  - ray idx 225, 289, 357
    - false hit. aimed at shrubs.
  - ray idx 243, 211, 58
    - false hit. because no stochasticity. shape error?

- packet idx 139
  - ray idx 147
    - large error. real near bush
  - ray idx 139, 207
    - false miss. if volumetric could've worked.
  - ray idx 359, 5, 265
    - medium/ large error. sim stopped by opaque shrub.
  - ray idx 219, 174
    - false miss. bad anno perhaps.
  - ray idx 101
    - good job. shrubs.
  - ray idx 88
    - false hit. sim hits tree. shape error.

- packet idx 573. example of good with ground triangles.

- packet idx 196. another good example of no perm
  - ray idx 368, 327, 261
    - false hit. aimed at shrub.
  - ray idx 308, 162, 305, 272
    - low error. hit version of 368. can say no stochasticity? no stoch, no
      perm, not volumetric.
  - ray idx 252, 286
    - false miss. bad anno. or due to surface nature.
  - ray idx 107
    - false miss. bad anno, or not enough ell in primitive.

----------------------------------------------------------------------------------------------------

* comparison

- packet idx 410
  - ray idx 201
    - both are similar
  - ray idx 176
    - hg does better because ell captures. mm tri cant capture, no vol.
  - ray idx 207
    - same comments as 176

- packet idx 695
  - ray idx 208
    - in shrubs. hg does better. mm gets caught earlier? both intersect, but hg
      can pass through due to permeability of models.
  - ray idx 210
    - in shrubs. both do medium.
  - ray idx 301
    - in shrubs. here mm does better. but hg has stochasticity :P
  - ray idx 85, 213
    - both large error. too much shrubs is bad anno?


- packet idx 219
  - ray idx 313
    - hg does better. captures via ellipsoids. mm passes through and hits
      faraway tree. could happen with ell too because of hit prob, but stoch
  - ray idx 243
    - hg does better. not a strong explanatory case though.
  - ray idx 107
    - both do good

- packet idx 9. excellent example of opacity in mm.
  - ray idx 207
    - both false miss. an anno issue?
  - ray idx 212
    - hg good job. mm false miss. candidate for hg better shape to environment.
  - ray idx 155
    - hg does better. faraway tree. mm is opaque tree.
  - ray idx 93
    - same tree. hg does better. mm misses because not volumetric.
  - ray idx 91
    - both do good.

- packet idx 654. here, ell gets the position-shape error right because trained
  on data. mm suffers. not sure what to say

- packet idx 654
  - ray idx 12, 163
    - both false hit. bad anno?
  - ray idx 357, 201, 268
    - mm, real hit ground. hg aggressively hits shrub ell. good example.
  - ray idx 278
    - hg does better. mm passes through to hit far veg.

- packet idx 122
  - ray idx 189
    - far tree. hg good job. mm false miss. good example of getting shape
      right + vol capture.
  - ray idx 21
    - mm gets true miss right. hg hits ell further down the line. good example
      of aggressive ell.
  - ray idx 211
    - both get lost in shrubbery.
  - ray idx 161
    - hg does better. not convincing.

- packet idx 90
  - ray idx 243, 308
    - hg does better. but looks like mm shape went wrong. maybe too clear-cut
      hedges.
  - ray idx 368, 162, 327, 261
    - mm also false hits. 

- packet idx 195. both screwed up here. hg large ell variance. mm opaque.
  - ray idx 46
    - example of large ell var. mm misses, insufficient shape.
  - ray idx 49
    - mm does better. hg suffers from large ell.
  - ray idx 305
    - hg good. mm misses.
  - ray idx 
  - ray idx 

- packet idx 
  - ray idx 
  - ray idx 
  - ray idx 
  - ray idx 
  - ray idx 
  - ray idx 

