primitiveClasses = ...
    {'low_shrub', 'low_shrub_patch', ...
    'small_shrub','small_shrub_patch', ...
    'medium_shrub', 'medium_shrub_patch', ...
    'large_shrub', 'large_shrub_patch', ...
    'small_tree', ...
    'medium_tree', ...
    'large_tree'};

nClasses = length(primitiveClasses);
primitiveClassIsPatch = zeros(1,nClasses);
for i = 1:nClasses
    posn = strfind(primitiveClasses{i},'patch');
    if isempty(posn)
        primitiveClassIsPatch(i) = 0;
    else
        primitiveClassIsPatch(i) = 1;
    end
end
    

save('../data/primitive_classes','primitiveClasses','primitiveClassIsPatch');