segmentToFeatureLabelMapping = ...
    [1 1 2 2 3 3 4 4 ...
    5 6 7];
relPathSegmentToFeatureLabelMapping = '../data/segment_to_feature_label_mapping';
save(relPathSegmentToFeatureLabelMapping,'segmentToFeatureLabelMapping');